trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.17'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
- script: ls $(Build.SourcesDirectory)/target
  displayName: 'Elenco dei file nella directory target'


# Assicurati che i file .war siano generati e posizionati nella cartella di destinazione
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/target'
    Contents: 'project-0.0.1-SNAPSHOT.war' # Specifica il nome esatto del file .war
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

# Aggiungi un passo per elencare i file, se necessario, per debugging
- script: ls $(Build.ArtifactStagingDirectory)
  displayName: 'Elenco dei file nella cartella di staging'
- script: find $(Build.SourcesDirectory) -type f
  displayName: 'Trova e elenca tutti i file nel directory sorgente'

- script: find $(Build.ArtifactStagingDirectory) -type f
  displayName: 'Trova e elenca tutti i file nella directory di staging'


# Pubblica l'artifact della build
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)' # Usa la cartella di staging dell'artifact come percorso da pubblicare
    ArtifactName: 'webapp' # Nome dell'artifact, cambiato per chiarezza
    publishLocation: 'Container' # Pubblica l'artifact nel contenitore di Azure DevOps
